import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const filepath = '../.output/server/package.json'
const data = require(filepath)
const fs = require('fs')

// Rewrite package.json generated by nuxt to fix node version and type:"module"
// otherwise cloud functions do not work
data.engines.node = '14'
// change entry point and add "type:module"
data.type = 'module'
data.main = './index.mjs'

fs.writeFile(
    process.cwd() + '/scripts/' + filepath,
    JSON.stringify(data, null, 2),
    (err) => {
        if (err) console.log(err)
        else {
            console.log(filepath + ' has been updated & written successfully\n')
        }
    }
)
